### ISSUE TITLE
Putting metrics fails when POWERTOOLS_METRICS_NAMESPACE is not set

### ISSUE THREAD

**Issue by roamingthings** [aws-powertools/powertools-lambda-java#1500]
Putting metrics will fail with an `software.amazon.cloudwatchlogs.emf.exception.InvalidNamespaceException` when environment `POWERTOOLS_METRICS_NAMESPACE` is not set.

**What were you trying to accomplish?**

After updating `cloudwatchlogs-aws-embedded-metrics` to 4.1.1 I started to get `InvalidNamespaceException` when I try to put a metric for example using

```
MetricsUtils.withSingleMetric("MyMetric, 1.0, Unit.COUNT, metric ->
...
});
```

## Expected Behavior
Possible behaviors I would expect are:
* metric is put with a default namespace
* no exception is thrown (maybe some internal logging). I would not expect a call to a metrics helper to fail my application with an unchecked exception

## Current Behavior

`software.amazon.cloudwatchlogs.emf.exception.InvalidNamespaceException` is thrown which is an unchecked expception.

The reason is that `MetricsUtils` sets the namespace to an empty string when the environment variable is not set:
```
    private static String defaultNameSpace() {
        MetricsContext context = MetricsLoggerHelper.metricsContext();
        return "aws-embedded-metrics".equals(context.getNamespace()) ?
                SystemWrapper.getenv("POWERTOOLS_METRICS_NAMESPACE") : context.getNamespace();
    }
```

## Possible Solution

* Keep the original default namespace (`aws-embedded-metrics`) if `POWERTOOLS_METRICS_NAMESPACE` is not set
* Choose another "default" namespace if `POWERTOOLS_METRICS_NAMESPACE` is not set

## Steps to Reproduce (for bugs)
1. Call `MetricsUtils.withSingleMetric()` whithout providing a namespace in `POWERTOOLS_METRICS_NAMESPACE`

## Environment

* **Powertools for AWS Lambda (Java) version used**: 1.17.0
* **Packaging format (Layers, Maven/Gradle)**: Gradle
* **AWS Lambda function runtime:** Java 17 (actually discovered in a unit test)
* **Debugging logs**

**Comment by scottgerring** [comment]
Hey @roamingthings , thanks for the report! The requirement for the variable [is documented[(https://docs.powertools.aws.dev/lambda/java/core/metrics/), but it does seem a bit odd to explicitly 1/ check if the default hasn't been overriden, and then 2/ override it with an empty string. Inverting the whole thing as you suggest so we override if we have the env var, or use the default otherwise, seems more sensible, and wouldn't be a breaking change. 

What do you think @jeromevdl  - ?

**Comment by jeromevdl** [comment]
First, I didn't really understand this code:
```
private static String defaultNameSpace() {
        MetricsContext context = MetricsLoggerHelper.metricsContext();
        return "aws-embedded-metrics".equals(context.getNamespace()) ?
                SystemWrapper.getenv("POWERTOOLS_METRICS_NAMESPACE") : context.getNamespace();
}
```
Looks to me that we should do the contrary: if the env var is empty, set a default, as you suggest. 

But I'm not sure how the context namespace is actually set. I've found [this](https://github.com/awslabs/aws-embedded-metrics-java/blob/ecbccd7e55e2ece08f8cb4f6512cef8bdfc12a7e/src/main/java/software/amazon/cloudwatchlogs/emf/model/MetricDirective.java#L49) which makes me think that `"aws-embedded-metrics"` is the default. So if it is the default, we try to replace it with the env var, otherwise, it means the user already changed the default somehow (how?) and we should use that.

What is missing here is the check on `SystemWrapper.getenv("POWERTOOLS_METRICS_NAMESPACE"`. If null or empty, we should come back to the default.
